# Generated by Django 2.0.2 on 2021-04-21 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='showthis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=150)),
                ('tasks', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sample.Item')),
            ],
        ),
    ]
