# Generated by Django 2.0.2 on 2021-04-21 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0002_showthis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showthis',
            name='tasks',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sample.Todolist'),
        ),
    ]
